### ISSUE TITLE
service_job_manager.py: Fails when called with no arguments

### ISSUE THREAD

**Issue by dpmayerUSGS** [USGS-Astrogeology/PDS-Pipelines#372]
**Description**
`service_job_manager.py` is typically called without any arguments, in which case it simply grabs the first key it sees in the job queue. However, it is now failing with the following error:
```
Traceback (most recent call last):
  File "pds_pipelines/service_job_manager.py", line 1036, in <module>
    sys.exit(main(parse_args()))
  File "pds_pipelines/service_job_manager.py", line 608, in main
    key = DBQO.jobKey()
  File "/home/pds2010mgr/anaconda3/envs/PDS-Services/lib/python3.7/site-packages/pds_pipelines/pds_db_query.py", line 67, in jobKey
    queryOBJ = self.session.query(self.processingTAB.key).filter(
AttributeError: 'sessionmaker' object has no attribute 'query'
```

**Steps to Reproduce**
`service_job_manager.py`

**Comment by jlaura** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#372](https://trello.com/c/di59y5HM/264-372)
