### ISSUE TITLE
service_final.py: TypeError When Size of ErrorHash > 0

### ISSUE THREAD

**Issue by dpmayerUSGS** [USGS-Astrogeology/PDS-Pipelines#387]
**Description**
`service_final.py` is supposed to be robust to cases where > 0 of the constituent images in a Service job failed for one reason or another. However, there's some sort of bug being triggered around the following line that causes the script to fail and exit when 1 or more images have errors
https://github.com/USGS-Astrogeology/PDS-Pipelines/blob/f59f4fcf8c7bf79029adbbd5b7d96e1dfe1c3a77/pds_pipelines/service_final.py#L103

That line is only executed if the size of the ErrorHash is > 0, so jobs in which all images processed normally are unaffected by this bug.

**Example Standard Error**
```
Traceback (most recent call last):
  File "/home/pds2010mgr/anaconda3/envs/PDS-Services/lib/python3.7/xml/etree/ElementTree.py", line 1067, in _escape_cdata
    if "&" in text:
TypeError: a bytes-like object is required, not 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usgs/cdev/PDS-Pipelines/pds_pipelines/service_final.py", line 296, in <module>
    sys.exit(main(parse_args()))
  File "/usgs/cdev/PDS-Pipelines/pds_pipelines/service_final.py", line 105, in main
    tree.write(fh, encoding='utf-8', xml_declaration=True)
  File "/home/pds2010mgr/anaconda3/envs/PDS-Services/lib/python3.7/xml/etree/ElementTree.py", line 777, in write
    short_empty_elements=short_empty_elements)
  File "/home/pds2010mgr/anaconda3/envs/PDS-Services/lib/python3.7/xml/etree/ElementTree.py", line 942, in _serialize_xml
    short_empty_elements=short_empty_elements)
  File "/home/pds2010mgr/anaconda3/envs/PDS-Services/lib/python3.7/xml/etree/ElementTree.py", line 942, in _serialize_xml
    short_empty_elements=short_empty_elements)
  File "/home/pds2010mgr/anaconda3/envs/PDS-Services/lib/python3.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
    write(_escape_cdata(text))
  File "/home/pds2010mgr/anaconda3/envs/PDS-Services/lib/python3.7/xml/etree/ElementTree.py", line 1075, in _escape_cdata
    _raise_serialization_error(text)
  File "/home/pds2010mgr/anaconda3/envs/PDS-Services/lib/python3.7/xml/etree/ElementTree.py", line 1058, in _raise_serialization_error
    "cannot serialize %r (type %s)" % (text, type(text).__name__)
TypeError: cannot serialize b'M1195777812LE' (type bytes)
```

**Expected Behavior**
`service_final.py` should report any images with errors to the jobs database, and then proceed to zip up the map template (if applicable), log files, and any images that did process successfully.

**Steps to Reproduce**
Submit a POW job with 1 or more images that will fail. For example, LROC NAC image submitting "M177909231LE"  and requesting output in POLAR STEROGRAPHIC projection will cause `cam2map` to balk, which is sufficient to trigger the error in `service_final.py`

**Comment by jlaura** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#387](https://trello.com/c/VvSGL5Kt/265-387)
